# Generated by Django 5.0.2 on 2024-04-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_editor_password_remove_editor_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='email',
        ),
    ]
