# Generated by Django 5.0.3 on 2024-04-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='problem_solved',
            field=models.BooleanField(default=False),
        ),
    ]
