# Generated by Django 5.0.2 on 2024-04-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_adminnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
