# Generated by Django 5.0.2 on 2024-04-05 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_editor_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminnotification',
            old_name='is_read',
            new_name='is_treated',
        ),
    ]
