# Generated by Django 5.0.2 on 2024-04-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_delete_useractionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='is_approved',
        ),
    ]
