# Generated by Django 5.0.2 on 2024-04-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_editor_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
