# Generated by Django 5.0.2 on 2024-04-09 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_customuser_is_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='profile_picture',
        ),
    ]
