<<<<<<< Updated upstream
# Generated by Django 5.0.2 on 2024-03-08 10:50

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_header_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='files',
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[blog.models.validate_file_extension]),
        ),
    ]
=======
# Generated by Django 5.0.2 on 2024-03-08 10:50

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_header_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='files',
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[blog.models.validate_file_extension]),
        ),
    ]
>>>>>>> Stashed changes
