<<<<<<< Updated upstream
# Generated by Django 5.0.2 on 2024-03-08 11:20

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_files_alter_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[blog.models.validate_file_extension]),
        ),
    ]
=======
# Generated by Django 5.0.2 on 2024-03-08 11:20

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_files_alter_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[blog.models.validate_file_extension]),
        ),
    ]
>>>>>>> Stashed changes
