# Generated by Django 5.0.2 on 2024-03-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('program', 'Program'), ('machines', 'Machines'), ('electrical', 'Electrical'), ('architectural', 'Architectural'), ('structural', 'Structural'), ('industrial', 'Industrial'), ('comp_science', 'Computer Science')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='department_choices',
            field=models.CharField(choices=[('program', 'Program'), ('machines', 'Machines'), ('electrical', 'Electrical'), ('architectural', 'Architectural'), ('structural', 'Structural'), ('industrial', 'Industrial'), ('comp_science', 'Computer Science')], default='tech', max_length=20),
        ),
    ]
