# Generated by Django 5.0.2 on 2024-03-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_choices_post_department_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='division',
            field=models.CharField(choices=[('program', 'הנדסת תוכנה'), ('machines', 'הנדסת מכונות'), ('electrical', 'הנדסת חשמל'), ('architectural', 'הנדסת אדריכלות'), ('structural', 'הנדסת בניין'), ('industrial', 'הנדסת תעשייה וניהול'), ('comp_science', 'מדעי המחשב')], max_length=20),
        ),
    ]
