# Generated by Django 5.0.2 on 2024-03-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_choices_division'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
