# Generated by Django 5.0.2 on 2024-03-24 10:45

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[blog.models.validate_file_extension, blog.models.sizefile]),
        ),
    ]
