# Generated by Django 5.0.3 on 2024-03-31 07:48

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file_comment_upload',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[blog.models.validate_file_extension, blog.models.sizefile]),
        ),
    ]
