# Generated by Django 5.0.3 on 2024-04-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_removalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('division', models.CharField(choices=[('program', 'Program'), ('machines', 'Machines'), ('electrical', 'Electrical'), ('architectural', 'Architectural'), ('structural', 'Structural'), ('industrial', 'Industrial'), ('comp_science', 'Computer Science')], max_length=100)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
