# Generated by Django 5.0.3 on 2024-04-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_post_department_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='department_choices',
            field=models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Architecture', 'Architecture'), ('Structural Engineering', 'Structural Engineering'), ('Industrial Engineering', 'Industrial Engineering'), ('Computer science', 'Computer science'), ('Chemical Engineering', 'Chemical Engineering')], default='tech', max_length=200),
        ),
        migrations.AlterField(
            model_name='studygroups',
            name='division',
            field=models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Architecture', 'Architecture'), ('Structural Engineering', 'Structural Engineering'), ('Industrial Engineering', 'Industrial Engineering'), ('Computer science', 'Computer science'), ('Chemical Engineering', 'Chemical Engineering')], max_length=100),
        ),
    ]
