# Generated by Django 5.0.3 on 2024-04-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_post_department_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isRight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='isevent',
            field=models.BooleanField(default=False),
        ),
    ]
