# Generated by Django 5.0.3 on 2024-04-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_post_isright_post_isevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='isRight',
            new_name='isbenefits',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='isevent',
            new_name='isright',
        ),
        migrations.AddField(
            model_name='post',
            name='benefits_rights_choices',
            field=models.CharField(choices=[('Exams', 'Exams'), ('Reserve', 'Reserve'), ('Events', 'Events')], max_length=100, null=True),
        ),
    ]
