# Generated by Django 5.0.3 on 2024-04-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_rename_isevents_post_isbenefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isreserve',
            field=models.BooleanField(default=False),
        ),
    ]
