# Generated by Django 5.0.3 on 2024-04-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_post_isreserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reserve_choices',
            field=models.CharField(choices=[('Preferred rights', 'Preferred rights'), ('Protection from dismissal', 'Protection from dismissal'), ('rates', 'rates')], max_length=100, null=True),
        ),
    ]
