# Generated by Django 5.0.3 on 2024-04-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_post_reserve_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
