# Generated by Django 5.0.2 on 2024-04-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_post_isanonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='benefits_choices',
            field=models.CharField(choices=[('Events', 'Events'), ('workshops', 'workshops'), ('Scholarships', 'Scholarships')], max_length=100, null=True),
        ),
    ]
