# Generated by Django 5.0.3 on 2024-04-07 01:25

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_problem_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_sumbit_upload',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[blog.models.validate_file_extension, blog.models.sizefile]),
        ),
    ]
