# Generated by Django 5.0.3 on 2024-04-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_alter_message_title_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='issue',
            field=models.BooleanField(default=False),
        ),
    ]
