# Generated by Django 5.0.4 on 2024-04-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_message_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
